const appname = "E-Mart";
const appversion = "Version 1.0.0";
const credits = "ISO : 2000,2010 Certified Company";
const email = "Email";
const emailHint = "admin@admin.com";
const password = "Password";
const passwordHint = "*****";
const forgetPass = "Forget Password";
const login = "Log in";
const signup = "Sign Up";
const createNewAccount = "or, create a new account";
const loginWith = "Log in with";
const reTypePassword = "Retype Password";
const name = "Name";
const nameHint = "Abhijit saha";
const privacyPolicy = "privacyPolicy";
const termAndCondition = "term & Condition";
const alreadyHaveAccount = "Already Have Account?";
const home = "Home";
const categories = "Categories";
const cart = "Cart";
const account = "Account";
const searchanything = "Search anything...",
    todaydeal = "Today's deal",
    flashsale = "Flash Sale",
    topsellers = "Top sellers",
    brand = "Brand",
    topcategories = "Top category",
    featuredcategory = "featured Category",
    womanDress = "woman Dress",
    girlsWatches = "girls Watches",
    mobilePhone = "mobile Phone",
    boysGlasses = "boys Glasses",
    tShirts = "tShirts",
    featuredProduct = "featured Product",
    girlsDress = "girls Dress";
